//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeriesManager {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Series : global::System.Configuration.ApplicationSettingsBase {
        
        private static Series defaultInstance = ((Series)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Series())));
        
        public static Series Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n    \"shows\": [\r\n        {\r\n            \"id\": \"9298\",\r\n            \"thetvdb_id\"" +
            ": \"283379\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"#CandidlyNicole\"," +
            "\r\n            \"seasons\": \"2\",\r\n            \"episodes\": \"40\",\r\n            \"follo" +
            "wers\": \"33\"\r\n        },\r\n        {\r\n            \"id\": \"5682\",\r\n            \"thet" +
            "vdb_id\": \"262240\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"#LaQuestio" +
            "nDeLaFin\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"35\",\r\n        " +
            "    \"followers\": \"231\"\r\n        },\r\n        {\r\n            \"id\": \"8222\",\r\n      " +
            "      \"thetvdb_id\": \"275658\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": " +
            "\"#RichKids of Beverly Hills\",\r\n            \"seasons\": \"2\",\r\n            \"episode" +
            "s\": \"19\",\r\n            \"followers\": \"38\"\r\n        },\r\n        {\r\n            \"id" +
            "\": \"2249\",\r\n            \"thetvdb_id\": \"164951\",\r\n            \"imdb_id\": \"tt16125" +
            "78\",\r\n            \"title\": \"$#*! My Dad Says\",\r\n            \"seasons\": \"1\",\r\n   " +
            "         \"episodes\": \"18\",\r\n            \"followers\": \"726\"\r\n        },\r\n        " +
            "{\r\n            \"id\": \"103\",\r\n            \"thetvdb_id\": \"73940\",\r\n            \"im" +
            "db_id\": \"tt0086659\",\r\n            \"title\": \"\'Allo \'Allo!\",\r\n            \"seasons" +
            "\": \"9\",\r\n            \"episodes\": \"83\",\r\n            \"followers\": \"60\"\r\n        }" +
            ",\r\n        {\r\n            \"id\": \"429\",\r\n            \"thetvdb_id\": \"79384\",\r\n    " +
            "        \"imdb_id\": \"tt0759475\",\r\n            \"title\": \"\'Til Death\",\r\n           " +
            " \"seasons\": \"4\",\r\n            \"episodes\": \"81\",\r\n            \"followers\": \"137\"\r" +
            "\n        },\r\n        {\r\n            \"id\": \"4625\",\r\n            \"thetvdb_id\": \"25" +
            "6633\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"+ ou - geek\",\r\n       " +
            "     \"seasons\": \"3\",\r\n            \"episodes\": \"64\",\r\n            \"followers\": \"1" +
            "66\"\r\n        },\r\n        {\r\n            \"id\": \"1736\",\r\n            \"thetvdb_id\":" +
            " \"79099\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \".hack\\/\\/\",\r\n      " +
            "      \"seasons\": \"3\",\r\n            \"episodes\": \"64\",\r\n            \"followers\": \"" +
            "370\"\r\n        },\r\n        {\r\n            \"id\": \"9127\",\r\n            \"thetvdb_id\"" +
            ": \"168681\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"0 Goshitsu no Kya" +
            "ku\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"22\",\r\n            \"f" +
            "ollowers\": \"1\"\r\n        },\r\n        {\r\n            \"id\": \"2145\",\r\n            \"t" +
            "hetvdb_id\": \"80814\",\r\n            \"imdb_id\": \"tt1025104\",\r\n            \"title\": " +
            "\"009-1\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"12\",\r\n          " +
            "  \"followers\": \"19\"\r\n        },\r\n        {\r\n            \"id\": \"1343\",\r\n         " +
            "   \"thetvdb_id\": \"88651\",\r\n            \"imdb_id\": \"tt1424033\",\r\n            \"tit" +
            "le\": \"07-Ghost\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"25\",\r\n  " +
            "          \"followers\": \"500\"\r\n        },\r\n        {\r\n            \"id\": \"3984\",\r\n" +
            "            \"thetvdb_id\": \"83111\",\r\n            \"imdb_id\": \"tt0494724\",\r\n       " +
            "     \"title\": \"1 Litre of Tears\",\r\n            \"seasons\": \"1\",\r\n            \"epi" +
            "sodes\": \"11\",\r\n            \"followers\": \"253\"\r\n        },\r\n        {\r\n          " +
            "  \"id\": \"4592\",\r\n            \"thetvdb_id\": \"212151\",\r\n            \"imdb_id\": \"\"," +
            "\r\n            \"title\": \"1 Night 2 Days\",\r\n            \"seasons\": \"3\",\r\n         " +
            "   \"episodes\": \"386\",\r\n            \"followers\": \"18\"\r\n        },\r\n        {\r\n   " +
            "         \"id\": \"3902\",\r\n            \"thetvdb_id\": \"116571\",\r\n            \"imdb_i" +
            "d\": \"tt1139478\",\r\n            \"title\": \"1 Pound no Fukuin\",\r\n            \"season" +
            "s\": \"1\",\r\n            \"episodes\": \"9\",\r\n            \"followers\": \"67\"\r\n        }" +
            ",\r\n        {\r\n            \"id\": \"5051\",\r\n            \"thetvdb_id\": \"258822\",\r\n  " +
            "          \"imdb_id\": \"\",\r\n            \"title\": \"10\",\r\n            \"seasons\": \"1\"" +
            ",\r\n            \"episodes\": \"10\",\r\n            \"followers\": \"5\"\r\n        },\r\n    " +
            "    {\r\n            \"id\": \"3015\",\r\n            \"thetvdb_id\": \"79599\",\r\n          " +
            "  \"imdb_id\": \"tt0826254\",\r\n            \"title\": \"10 Items Or Less\",\r\n           " +
            " \"seasons\": \"3\",\r\n            \"episodes\": \"21\",\r\n            \"followers\": \"7\"\r\n " +
            "       },\r\n        {\r\n            \"id\": \"8203\",\r\n            \"thetvdb_id\": \"2772" +
            "27\",\r\n            \"imdb_id\": \"tt2490294\",\r\n            \"title\": \"10 Million Doll" +
            "ar Bigfoot Bounty\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"8\",\r\n" +
            "            \"followers\": \"5\"\r\n        },\r\n        {\r\n            \"id\": \"7674\",\r\n" +
            "            \"thetvdb_id\": \"274125\",\r\n            \"imdb_id\": \"\",\r\n            \"ti" +
            "tle\": \"10 Minutes \\u00e0 perdre\",\r\n            \"seasons\": \"1\",\r\n            \"epi" +
            "sodes\": \"178\",\r\n            \"followers\": \"26\"\r\n        },\r\n        {\r\n          " +
            "  \"id\": \"2680\",\r\n            \"thetvdb_id\": \"221001\",\r\n            \"imdb_id\": \"tt" +
            "1811399\",\r\n            \"title\": \"10 O\'Clock Live\",\r\n            \"seasons\": \"3\",\r" +
            "\n            \"episodes\": \"33\",\r\n            \"followers\": \"17\"\r\n        },\r\n     " +
            "   {\r\n            \"id\": \"774\",\r\n            \"thetvdb_id\": \"95761\",\r\n            " +
            "\"imdb_id\": \"tt1321805\",\r\n            \"title\": \"10 Things I Hate About You\",\r\n   " +
            "         \"seasons\": \"1\",\r\n            \"episodes\": \"20\",\r\n            \"followers\"" +
            ": \"2153\"\r\n        },\r\n        {\r\n            \"id\": \"2436\",\r\n            \"thetvdb" +
            "_id\": \"72098\",\r\n            \"imdb_id\": \"tt0365969\",\r\n            \"title\": \"10-8\"" +
            ",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"15\",\r\n            \"foll" +
            "owers\": \"8\"\r\n        },\r\n        {\r\n            \"id\": \"9756\",\r\n            \"thet" +
            "vdb_id\": \"79314\",\r\n            \"imdb_id\": \"tt0463850\",\r\n            \"title\": \"10" +
            ".5 Apocalypse\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"2\",\r\n    " +
            "        \"followers\": \"0\"\r\n        },\r\n        {\r\n            \"id\": \"1476\",\r\n    " +
            "        \"thetvdb_id\": \"72450\",\r\n            \"imdb_id\": \"tt0218744\",\r\n           " +
            " \"title\": \"100 Deeds for Eddie McDowd\",\r\n            \"seasons\": \"3\",\r\n          " +
            "  \"episodes\": \"40\",\r\n            \"followers\": \"37\"\r\n        },\r\n        {\r\n     " +
            "       \"id\": \"1467\",\r\n            \"thetvdb_id\": \"94581\",\r\n            \"imdb_id\":" +
            " \"tt1441093\",\r\n            \"title\": \"100 Questions\",\r\n            \"seasons\": \"1\"" +
            ",\r\n            \"episodes\": \"6\",\r\n            \"followers\": \"483\"\r\n        },\r\n   " +
            "     {\r\n            \"id\": \"9860\",\r\n            \"thetvdb_id\": \"288031\",\r\n        " +
            "    \"imdb_id\": \"\",\r\n            \"title\": \"100% comestible\",\r\n            \"season" +
            "s\": \"4\",\r\n            \"episodes\": \"99\",\r\n            \"followers\": \"2\"\r\n        }" +
            ",\r\n        {\r\n            \"id\": \"10740\",\r\n            \"thetvdb_id\": \"291981\",\r\n " +
            "           \"imdb_id\": \"\",\r\n            \"title\": \"1000 Days for the Planet: Human" +
            " Adventure\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"7\",\r\n       " +
            "     \"followers\": \"1\"\r\n        },\r\n        {\r\n            \"id\": \"3640\",\r\n       " +
            "     \"thetvdb_id\": \"82083\",\r\n            \"imdb_id\": \"tt1105711\",\r\n            \"t" +
            "itle\": \"1000 Ways To Die\",\r\n            \"seasons\": \"6\",\r\n            \"episodes\":" +
            " \"94\",\r\n            \"followers\": \"30\"\r\n        },\r\n        {\r\n            \"id\": " +
            "\"7961\",\r\n            \"thetvdb_id\": \"96531\",\r\n            \"imdb_id\": \"tt1329539\"," +
            "\r\n            \"title\": \"1066: The Battle for Middle Earth\",\r\n            \"season" +
            "s\": \"1\",\r\n            \"episodes\": \"3\",\r\n            \"followers\": \"4\"\r\n        }," +
            "\r\n        {\r\n            \"id\": \"10212\",\r\n            \"thetvdb_id\": \"290194\",\r\n  " +
            "          \"imdb_id\": \"tt2879552\",\r\n            \"title\": \"11\\/22\\/63\",\r\n         " +
            "   \"seasons\": \"0\",\r\n            \"episodes\": \"0\",\r\n            \"followers\": \"55\"\r" +
            "\n        },\r\n        {\r\n            \"id\": \"1044\",\r\n            \"thetvdb_id\": \"11" +
            "7851\",\r\n            \"imdb_id\": \"tt1515976\",\r\n            \"title\": \"11eyes\",\r\n   " +
            "         \"seasons\": \"1\",\r\n            \"episodes\": \"12\",\r\n            \"followers\"" +
            ": \"218\"\r\n        },\r\n        {\r\n            \"id\": \"7791\",\r\n            \"thetvdb_" +
            "id\": \"272644\",\r\n            \"imdb_id\": \"tt3148266\",\r\n            \"title\": \"12 Mo" +
            "nkeys\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"12\",\r\n           " +
            " \"followers\": \"7753\"\r\n        },\r\n        {\r\n            \"id\": \"10329\",\r\n       " +
            "     \"thetvdb_id\": \"289796\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"" +
            "12-Sai.: Kiss, Kirai, Suki\",\r\n            \"seasons\": \"0\",\r\n            \"episodes" +
            "\": \"0\",\r\n            \"followers\": \"0\"\r\n        },\r\n        {\r\n            \"id\": " +
            "\"567\",\r\n            \"thetvdb_id\": \"84468\",\r\n            \"imdb_id\": \"tt1204828\",\r" +
            "\n            \"title\": \"13 - Fear is Real\",\r\n            \"seasons\": \"1\",\r\n       " +
            "     \"episodes\": \"8\",\r\n            \"followers\": \"14\"\r\n        },\r\n        {\r\n   " +
            "         \"id\": \"9144\",\r\n            \"thetvdb_id\": \"281374\",\r\n            \"imdb_i" +
            "d\": \"tt3543084\",\r\n            \"title\": \"14 - Des armes et des mots\",\r\n          " +
            "  \"seasons\": \"1\",\r\n            \"episodes\": \"8\",\r\n            \"followers\": \"4\"\r\n " +
            "       },\r\n        {\r\n            \"id\": \"4146\",\r\n            \"thetvdb_id\": \"1044" +
            "11\",\r\n            \"imdb_id\": \"tt0969666\",\r\n            \"title\": \"14 Sai no Haha\"" +
            ",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"11\",\r\n            \"foll" +
            "owers\": \"145\"\r\n        },\r\n        {\r\n            \"id\": \"7909\",\r\n            \"th" +
            "etvdb_id\": \"72339\",\r\n            \"imdb_id\": \"tt0354262\",\r\n            \"title\": \"" +
            "15 Storeys High\",\r\n            \"seasons\": \"2\",\r\n            \"episodes\": \"12\",\r\n " +
            "           \"followers\": \"2\"\r\n        },\r\n        {\r\n            \"id\": \"3645\",\r\n " +
            "           \"thetvdb_id\": \"72941\",\r\n            \"imdb_id\": \"\",\r\n            \"titl" +
            "e\": \"15\\/Love\",\r\n            \"seasons\": \"3\",\r\n            \"episodes\": \"54\",\r\n   " +
            "         \"followers\": \"253\"\r\n        },\r\n        {\r\n            \"id\": \"8801\",\r\n " +
            "           \"thetvdb_id\": \"280338\",\r\n            \"imdb_id\": \"\",\r\n            \"tit" +
            "le\": \"15000 Kids and Counting\",\r\n            \"seasons\": \"1\",\r\n            \"episo" +
            "des\": \"1\",\r\n            \"followers\": \"2\"\r\n        },\r\n        {\r\n            \"id" +
            "\": \"4166\",\r\n            \"thetvdb_id\": \"126011\",\r\n            \"imdb_id\": \"tt14547" +
            "30\",\r\n            \"title\": \"16 and Pregnant\",\r\n            \"seasons\": \"5\",\r\n    " +
            "        \"episodes\": \"72\",\r\n            \"followers\": \"87\"\r\n        },\r\n        {\r" +
            "\n            \"id\": \"6490\",\r\n            \"thetvdb_id\": \"267921\",\r\n            \"im" +
            "db_id\": \"\",\r\n            \"title\": \"16 Kids and Counting\",\r\n            \"seasons\"" +
            ": \"1\",\r\n            \"episodes\": \"7\",\r\n            \"followers\": \"1\"\r\n        },\r\n" +
            "        {\r\n            \"id\": \"8328\",\r\n            \"thetvdb_id\": \"262926\",\r\n     " +
            "       \"imdb_id\": \"\",\r\n            \"title\": \"16-Bit Gems\",\r\n            \"seasons" +
            "\": \"4\",\r\n            \"episodes\": \"36\",\r\n            \"followers\": \"0\"\r\n        }," +
            "\r\n        {\r\n            \"id\": \"5072\",\r\n            \"thetvdb_id\": \"259016\",\r\n   " +
            "         \"imdb_id\": \"tt2266639\",\r\n            \"title\": \"1600 Penn\",\r\n           " +
            " \"seasons\": \"1\",\r\n            \"episodes\": \"13\",\r\n            \"followers\": \"609\"\r" +
            "\n        },\r\n        {\r\n            \"id\": \"4917\",\r\n            \"thetvdb_id\": \"22" +
            "3791\",\r\n            \"imdb_id\": \"tt1563584\",\r\n            \"title\": \"1788...et dem" +
            "i\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"6\",\r\n            \"fol" +
            "lowers\": \"40\"\r\n        },\r\n        {\r\n            \"id\": \"609\",\r\n            \"the" +
            "tvdb_id\": \"250615\",\r\n            \"imdb_id\": \"tt1828937\",\r\n            \"title\": \"" +
            "17th precinct\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"1\",\r\n    " +
            "        \"followers\": \"22\"\r\n        },\r\n        {\r\n            \"id\": \"76\",\r\n     " +
            "       \"thetvdb_id\": \"132781\",\r\n            \"imdb_id\": \"tt1411254\",\r\n           " +
            " \"title\": \"18 To Life\",\r\n            \"seasons\": \"2\",\r\n            \"episodes\": \"2" +
            "5\",\r\n            \"followers\": \"248\"\r\n        },\r\n        {\r\n            \"id\": \"5" +
            "874\",\r\n            \"thetvdb_id\": \"261237\",\r\n            \"imdb_id\": \"\",\r\n        " +
            "    \"title\": \"18 vs. 29\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": " +
            "\"16\",\r\n            \"followers\": \"12\"\r\n        },\r\n        {\r\n            \"id\": \"" +
            "9980\",\r\n            \"thetvdb_id\": \"286287\",\r\n            \"imdb_id\": \"tt1753353\"," +
            "\r\n            \"title\": \"1864\",\r\n            \"seasons\": \"1\",\r\n            \"episod" +
            "es\": \"8\",\r\n            \"followers\": \"15\"\r\n        },\r\n        {\r\n            \"id" +
            "\": \"5508\",\r\n            \"thetvdb_id\": \"139481\",\r\n            \"imdb_id\": \"tt13070" +
            "83\",\r\n            \"title\": \"19 Kids and Counting\",\r\n            \"seasons\": \"9\",\r" +
            "\n            \"episodes\": \"229\",\r\n            \"followers\": \"22\"\r\n        },\r\n    " +
            "    {\r\n            \"id\": \"107\",\r\n            \"thetvdb_id\": \"216271\",\r\n          " +
            "  \"imdb_id\": \"tt1840973\",\r\n            \"title\": \"19-2\",\r\n            \"seasons\": " +
            "\"3\",\r\n            \"episodes\": \"30\",\r\n            \"followers\": \"311\"\r\n        },\r" +
            "\n        {\r\n            \"id\": \"8087\",\r\n            \"thetvdb_id\": \"276360\",\r\n    " +
            "        \"imdb_id\": \"tt3340712\",\r\n            \"title\": \"19-2 (2014)\",\r\n          " +
            "  \"seasons\": \"2\",\r\n            \"episodes\": \"20\",\r\n            \"followers\": \"110\"" +
            "\r\n        },\r\n        {\r\n            \"id\": \"10708\",\r\n            \"thetvdb_id\": \"" +
            "292192\",\r\n            \"imdb_id\": \"tt2983290\",\r\n            \"title\": \"1992\",\r\n   " +
            "         \"seasons\": \"1\",\r\n            \"episodes\": \"4\",\r\n            \"followers\":" +
            " \"1\"\r\n        },\r\n        {\r\n            \"id\": \"3318\",\r\n            \"thetvdb_id\"" +
            ": \"248741\",\r\n            \"imdb_id\": \"tt1845307\",\r\n            \"title\": \"2 Broke " +
            "Girls\",\r\n            \"seasons\": \"4\",\r\n            \"episodes\": \"88\",\r\n           " +
            " \"followers\": \"19694\"\r\n        },\r\n        {\r\n            \"id\": \"6980\",\r\n       " +
            "     \"thetvdb_id\": \"259382\",\r\n            \"imdb_id\": \"tt0220955\",\r\n            \"" +
            "title\": \"2 fr\\u00e8res\",\r\n            \"seasons\": \"2\",\r\n            \"episodes\": \"" +
            "24\",\r\n            \"followers\": \"2\"\r\n        },\r\n        {\r\n            \"id\": \"82" +
            "4\",\r\n            \"thetvdb_id\": \"77585\",\r\n            \"imdb_id\": \"tt0092312\",\r\n  " +
            "          \"title\": \"21 Jump Street\",\r\n            \"seasons\": \"5\",\r\n            \"" +
            "episodes\": \"103\",\r\n            \"followers\": \"976\"\r\n        },\r\n        {\r\n      " +
            "      \"id\": \"9074\",\r\n            \"thetvdb_id\": \"258155\",\r\n            \"imdb_id\":" +
            " \"\",\r\n            \"title\": \"21st Century Family\",\r\n            \"seasons\": \"1\",\r\n" +
            "            \"episodes\": \"8\",\r\n            \"followers\": \"1\"\r\n        },\r\n        " +
            "{\r\n            \"id\": \"9\",\r\n            \"thetvdb_id\": \"76290\",\r\n            \"imdb" +
            "_id\": \"tt0285331\",\r\n            \"title\": \"24\",\r\n            \"seasons\": \"9\",\r\n   " +
            "         \"episodes\": \"205\",\r\n            \"followers\": \"20866\"\r\n        },\r\n     " +
            "   {\r\n            \"id\": \"8995\",\r\n            \"thetvdb_id\": \"248699\",\r\n          " +
            "  \"imdb_id\": \"tt2674484\",\r\n            \"title\": \"24 Hours in A&E\",\r\n            " +
            "\"seasons\": \"8\",\r\n            \"episodes\": \"91\",\r\n            \"followers\": \"4\"\r\n  " +
            "      },\r\n        {\r\n            \"id\": \"6767\",\r\n            \"thetvdb_id\": \"26643" +
            "2\",\r\n            \"imdb_id\": \"tt2874044\",\r\n            \"title\": \"24CH\",\r\n        " +
            "    \"seasons\": \"3\",\r\n            \"episodes\": \"60\",\r\n            \"followers\": \"84" +
            "\"\r\n        },\r\n        {\r\n            \"id\": \"8305\",\r\n            \"thetvdb_id\": \"" +
            "278803\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"26 lettres\",\r\n      " +
            "      \"seasons\": \"0\",\r\n            \"episodes\": \"0\",\r\n            \"followers\": \"3" +
            "\"\r\n        },\r\n        {\r\n            \"id\": \"7637\",\r\n            \"thetvdb_id\": \"" +
            "77935\",\r\n            \"imdb_id\": \"tt0298617\",\r\n            \"title\": \"2DTV\",\r\n    " +
            "        \"seasons\": \"5\",\r\n            \"episodes\": \"34\",\r\n            \"followers\":" +
            " \"1\"\r\n        },\r\n        {\r\n            \"id\": \"8965\",\r\n            \"thetvdb_id\"" +
            ": \"218661\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"2NE1 TV\",\r\n      " +
            "      \"seasons\": \"0\",\r\n            \"episodes\": \"0\",\r\n            \"followers\": \"3" +
            "\"\r\n        },\r\n        {\r\n            \"id\": \"1671\",\r\n            \"thetvdb_id\": \"" +
            "84119\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"2x2 = Shinobuden\",\r\n " +
            "           \"seasons\": \"1\",\r\n            \"episodes\": \"12\",\r\n            \"follower" +
            "s\": \"22\"\r\n        },\r\n        {\r\n            \"id\": \"8393\",\r\n            \"thetvdb" +
            "_id\": \"278755\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"3 Days\",\r\n   " +
            "         \"seasons\": \"1\",\r\n            \"episodes\": \"16\",\r\n            \"followers\"" +
            ": \"22\"\r\n        },\r\n        {\r\n            \"id\": \"47\",\r\n            \"thetvdb_id\"" +
            ": \"75555\",\r\n            \"imdb_id\": \"tt0775558\",\r\n            \"title\": \"3 Lbs\",\r\n" +
            "            \"seasons\": \"1\",\r\n            \"episodes\": \"8\",\r\n            \"follower" +
            "s\": \"21\"\r\n        },\r\n        {\r\n            \"id\": \"4568\",\r\n            \"thetvdb" +
            "_id\": \"250943\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"3 Minute Wond" +
            "er With Karl Pilkington\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": " +
            "\"4\",\r\n            \"followers\": \"3\"\r\n        },\r\n        {\r\n            \"id\": \"77" +
            "48\",\r\n            \"thetvdb_id\": \"71712\",\r\n            \"imdb_id\": \"\",\r\n          " +
            "  \"title\": \"3 South\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"13\"" +
            ",\r\n            \"followers\": \"1\"\r\n        },\r\n        {\r\n            \"id\": \"2940\"" +
            ",\r\n            \"thetvdb_id\": \"250038\",\r\n            \"imdb_id\": \"\",\r\n            " +
            "\"title\": \"3 Way\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"12\",\r\n " +
            "           \"followers\": \"10\"\r\n        },\r\n        {\r\n            \"id\": \"8648\",\r\n" +
            "            \"thetvdb_id\": \"280551\",\r\n            \"imdb_id\": \"tt3556544\",\r\n      " +
            "      \"title\": \"3 x Manon\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\"" +
            ": \"3\",\r\n            \"followers\": \"145\"\r\n        },\r\n        {\r\n            \"id\":" +
            " \"5948\",\r\n            \"thetvdb_id\": \"78818\",\r\n            \"imdb_id\": \"tt0437696\"" +
            ",\r\n            \"title\": \"30 Days\",\r\n            \"seasons\": \"3\",\r\n            \"ep" +
            "isodes\": \"18\",\r\n            \"followers\": \"5\"\r\n        },\r\n        {\r\n           " +
            " \"id\": \"8107\",\r\n            \"thetvdb_id\": \"81527\",\r\n            \"imdb_id\": \"tt10" +
            "78298\",\r\n            \"title\": \"30 Days Of Night: Blood Trails\",\r\n            \"se" +
            "asons\": \"1\",\r\n            \"episodes\": \"7\",\r\n            \"followers\": \"6\"\r\n      " +
            "  },\r\n        {\r\n            \"id\": \"8080\",\r\n            \"thetvdb_id\": \"85216\",\r\n" +
            "            \"imdb_id\": \"tt1245687\",\r\n            \"title\": \"30 Days Of Night: Dus" +
            "t To Dust\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"6\",\r\n        " +
            "    \"followers\": \"10\"\r\n        },\r\n        {\r\n            \"id\": \"6695\",\r\n       " +
            "     \"thetvdb_id\": \"255912\",\r\n            \"imdb_id\": \"tt1677734\",\r\n            \"" +
            "title\": \"30 Grader i Februari\",\r\n            \"seasons\": \"1\",\r\n            \"episo" +
            "des\": \"10\",\r\n            \"followers\": \"17\"\r\n        },\r\n        {\r\n            \"" +
            "id\": \"48\",\r\n            \"thetvdb_id\": \"79488\",\r\n            \"imdb_id\": \"tt049642" +
            "4\",\r\n            \"title\": \"30 Rock\",\r\n            \"seasons\": \"7\",\r\n            \"" +
            "episodes\": \"138\",\r\n            \"followers\": \"6120\"\r\n        },\r\n        {\r\n     " +
            "       \"id\": \"6857\",\r\n            \"thetvdb_id\": \"259507\",\r\n            \"imdb_id\"" +
            ": \"\",\r\n            \"title\": \"30 Shekel per hour\",\r\n            \"seasons\": \"2\",\r\n" +
            "            \"episodes\": \"18\",\r\n            \"followers\": \"5\"\r\n        },\r\n       " +
            " {\r\n            \"id\": \"5928\",\r\n            \"thetvdb_id\": \"238461\",\r\n            " +
            "\"imdb_id\": \"tt1851101\",\r\n            \"title\": \"30 Vies\",\r\n            \"seasons\":" +
            " \"2\",\r\n            \"episodes\": \"48\",\r\n            \"followers\": \"41\"\r\n        },\r" +
            "\n        {\r\n            \"id\": \"5183\",\r\n            \"thetvdb_id\": \"137801\",\r\n    " +
            "        \"imdb_id\": \"\",\r\n            \"title\": \"3000 Leagues in Search of Mother\"," +
            "\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"52\",\r\n            \"follo" +
            "wers\": \"1\"\r\n        },\r\n        {\r\n            \"id\": \"9272\",\r\n            \"thetv" +
            "db_id\": \"244751\",\r\n            \"imdb_id\": \"tt1874838\",\r\n            \"title\": \"32" +
            " Brinkburn Street\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"5\",\r\n" +
            "            \"followers\": \"1\"\r\n        },\r\n        {\r\n            \"id\": \"7188\",\r\n" +
            "            \"thetvdb_id\": \"268759\",\r\n            \"imdb_id\": \"tt2727308\",\r\n      " +
            "      \"title\": \"35 Sai no Koukousei\",\r\n            \"seasons\": \"1\",\r\n            " +
            "\"episodes\": \"11\",\r\n            \"followers\": \"30\"\r\n        },\r\n        {\r\n       " +
            "     \"id\": \"6045\",\r\n            \"thetvdb_id\": \"264579\",\r\n            \"imdb_id\": " +
            "\"\",\r\n            \"title\": \"360 minutes pour survivre\",\r\n            \"seasons\": \"" +
            "0\",\r\n            \"episodes\": \"0\",\r\n            \"followers\": \"5\"\r\n        },\r\n   " +
            "     {\r\n            \"id\": \"6211\",\r\n            \"thetvdb_id\": \"266314\",\r\n        " +
            "    \"imdb_id\": \"\",\r\n            \"title\": \"3615 Research & Development\",\r\n       " +
            "     \"seasons\": \"1\",\r\n            \"episodes\": \"16\",\r\n            \"followers\": \"2" +
            "29\"\r\n        },\r\n        {\r\n            \"id\": \"4979\",\r\n            \"thetvdb_id\":" +
            " \"258568\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"3615 Usul\",\r\n     " +
            "       \"seasons\": \"2\",\r\n            \"episodes\": \"89\",\r\n            \"followers\": " +
            "\"1572\"\r\n        },\r\n        {\r\n            \"id\": \"8354\",\r\n            \"thetvdb_i" +
            "d\": \"274115\",\r\n            \"imdb_id\": \"tt3101352\",\r\n            \"title\": \"37 Day" +
            "s\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"3\",\r\n            \"fol" +
            "lowers\": \"11\"\r\n        },\r\n        {\r\n            \"id\": \"1064\",\r\n            \"th" +
            "etvdb_id\": \"72389\",\r\n            \"imdb_id\": \"tt0115082\",\r\n            \"title\": \"" +
            "3rd Rock from the Sun\",\r\n            \"seasons\": \"6\",\r\n            \"episodes\": \"1" +
            "39\",\r\n            \"followers\": \"284\"\r\n        },\r\n        {\r\n            \"id\": \"" +
            "1344\",\r\n            \"thetvdb_id\": \"70973\",\r\n            \"imdb_id\": \"\",\r\n        " +
            "    \"title\": \"3x3 Eyes\",\r\n            \"seasons\": \"2\",\r\n            \"episodes\": \"" +
            "7\",\r\n            \"followers\": \"67\"\r\n        },\r\n        {\r\n            \"id\": \"55" +
            "95\",\r\n            \"thetvdb_id\": \"258582\",\r\n            \"imdb_id\": \"tt0149407\",\r\n" +
            "            \"title\": \"4 et demi...\",\r\n            \"seasons\": \"7\",\r\n            \"" +
            "episodes\": \"193\",\r\n            \"followers\": \"15\"\r\n        },\r\n        {\r\n       " +
            "     \"id\": \"5550\",\r\n            \"thetvdb_id\": \"259882\",\r\n            \"imdb_id\": " +
            "\"\",\r\n            \"title\": \"42\\u00e8me \\u00e9tage\",\r\n            \"seasons\": \"2\",\r" +
            "\n            \"episodes\": \"8\",\r\n            \"followers\": \"152\"\r\n        },\r\n     " +
            "   {\r\n            \"id\": \"6545\",\r\n            \"thetvdb_id\": \"178551\",\r\n          " +
            "  \"imdb_id\": \"tt0388571\",\r\n            \"title\": \"450 Chemin du golf\",\r\n         " +
            "   \"seasons\": \"7\",\r\n            \"episodes\": \"141\",\r\n            \"followers\": \"4\"" +
            "\r\n        },\r\n        {\r\n            \"id\": \"9453\",\r\n            \"thetvdb_id\": \"2" +
            "73955\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"49\",\r\n            \"se" +
            "asons\": \"1\",\r\n            \"episodes\": \"11\",\r\n            \"followers\": \"1\"\r\n     " +
            "   },\r\n        {\r\n            \"id\": \"3982\",\r\n            \"thetvdb_id\": \"245521\"," +
            "\r\n            \"imdb_id\": \"tt1935066\",\r\n            \"title\": \"49 Days\",\r\n        " +
            "    \"seasons\": \"1\",\r\n            \"episodes\": \"20\",\r\n            \"followers\": \"10" +
            "0\"\r\n        },\r\n        {\r\n            \"id\": \"5961\",\r\n            \"thetvdb_id\": " +
            "\"84110\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"50 Cent: The Money a" +
            "nd The Power\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"10\",\r\n    " +
            "        \"followers\": \"2\"\r\n        },\r\n        {\r\n            \"id\": \"3606\",\r\n    " +
            "        \"thetvdb_id\": \"73801\",\r\n            \"imdb_id\": \"tt0397756\",\r\n           " +
            " \"title\": \"55 degr\\u00e9s nord\",\r\n            \"seasons\": \"2\",\r\n            \"epis" +
            "odes\": \"14\",\r\n            \"followers\": \"6\"\r\n        },\r\n        {\r\n            \"" +
            "id\": \"7839\",\r\n            \"thetvdb_id\": \"79546\",\r\n            \"imdb_id\": \"tt0386" +
            "907\",\r\n            \"title\": \"5ive Days to Midnight\",\r\n            \"seasons\": \"1\"" +
            ",\r\n            \"episodes\": \"5\",\r\n            \"followers\": \"1\"\r\n        },\r\n     " +
            "   {\r\n            \"id\": \"8172\",\r\n            \"thetvdb_id\": \"123601\",\r\n          " +
            "  \"imdb_id\": \"\",\r\n            \"title\": \"6 Angels\",\r\n            \"seasons\": \"1\",\r" +
            "\n            \"episodes\": \"6\",\r\n            \"followers\": \"0\"\r\n        },\r\n       " +
            " {\r\n            \"id\": \"4813\",\r\n            \"thetvdb_id\": \"256204\",\r\n            " +
            "\"imdb_id\": \"tt2197797\",\r\n            \"title\": \"666 Park Avenue\",\r\n            \"s" +
            "easons\": \"1\",\r\n            \"episodes\": \"13\",\r\n            \"followers\": \"5337\"\r\n " +
            "       },\r\n        {\r\n            \"id\": \"6312\",\r\n            \"thetvdb_id\": \"7544" +
            "4\",\r\n            \"imdb_id\": \"tt0439341\",\r\n            \"title\": \"6teen\",\r\n       " +
            "     \"seasons\": \"4\",\r\n            \"episodes\": \"91\",\r\n            \"followers\": \"6" +
            "\"\r\n        },\r\n        {\r\n            \"id\": \"603\",\r\n            \"thetvdb_id\": \"7" +
            "4540\",\r\n            \"imdb_id\": \"tt0167720\",\r\n            \"title\": \"7 Days\",\r\n   " +
            "         \"seasons\": \"3\",\r\n            \"episodes\": \"66\",\r\n            \"followers\"" +
            ": \"358\"\r\n        },\r\n        {\r\n            \"id\": \"3557\",\r\n            \"thetvdb_" +
            "id\": \"225121\",\r\n            \"imdb_id\": null,\r\n            \"title\": \"7 Days In Li" +
            "fe\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"19\",\r\n            \"f" +
            "ollowers\": \"0\"\r\n        },\r\n        {\r\n            \"id\": \"9419\",\r\n            \"t" +
            "hetvdb_id\": \"282547\",\r\n            \"imdb_id\": \"tt3735164\",\r\n            \"title\":" +
            " \"7 Deadly Sins\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"7\",\r\n  " +
            "          \"followers\": \"59\"\r\n        },\r\n        {\r\n            \"id\": \"923\",\r\n  " +
            "          \"thetvdb_id\": \"83853\",\r\n            \"imdb_id\": \"tt0192877\",\r\n         " +
            "   \"title\": \"7 Vidas\",\r\n            \"seasons\": \"14\",\r\n            \"episodes\": \"2" +
            "64\",\r\n            \"followers\": \"13\"\r\n        },\r\n        {\r\n            \"id\": \"6" +
            "972\",\r\n            \"thetvdb_id\": \"270173\",\r\n            \"imdb_id\": \"\",\r\n        " +
            "    \"title\": \"72 Hours\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"" +
            "8\",\r\n            \"followers\": \"7\"\r\n        },\r\n        {\r\n            \"id\": \"624" +
            "6\",\r\n            \"thetvdb_id\": \"265605\",\r\n            \"imdb_id\": \"tt3061226\",\r\n " +
            "           \"title\": \"7th Grade Civil Servant\",\r\n            \"seasons\": \"1\",\r\n   " +
            "         \"episodes\": \"20\",\r\n            \"followers\": \"121\"\r\n        },\r\n        " +
            "{\r\n            \"id\": \"645\",\r\n            \"thetvdb_id\": \"73928\",\r\n            \"im" +
            "db_id\": \"tt0115083\",\r\n            \"title\": \"7th Heaven\",\r\n            \"seasons\":" +
            " \"11\",\r\n            \"episodes\": \"243\",\r\n            \"followers\": \"2213\"\r\n       " +
            " },\r\n        {\r\n            \"id\": \"8800\",\r\n            \"thetvdb_id\": \"79556\",\r\n " +
            "           \"imdb_id\": \"tt0465315\",\r\n            \"title\": \"8 Out of 10 Cats\",\r\n  " +
            "          \"seasons\": \"18\",\r\n            \"episodes\": \"174\",\r\n            \"followe" +
            "rs\": \"14\"\r\n        },\r\n        {\r\n            \"id\": \"7562\",\r\n            \"thetvd" +
            "b_id\": \"272156\",\r\n            \"imdb_id\": \"tt2345459\",\r\n            \"title\": \"8 O" +
            "ut of 10 Cats Does Countdown\",\r\n            \"seasons\": \"7\",\r\n            \"episod" +
            "es\": \"31\",\r\n            \"followers\": \"17\"\r\n        },\r\n        {\r\n            \"i" +
            "d\": \"424\",\r\n            \"thetvdb_id\": \"78461\",\r\n            \"imdb_id\": \"tt031208" +
            "1\",\r\n            \"title\": \"8 Simple Rules\",\r\n            \"seasons\": \"3\",\r\n      " +
            "      \"episodes\": \"76\",\r\n            \"followers\": \"1042\"\r\n        },\r\n        {\r" +
            "\n            \"id\": \"222\",\r\n            \"thetvdb_id\": \"120031\",\r\n            \"imd" +
            "b_id\": \"tt0109143\",\r\n            \"title\": \"801 T.T.S. Airbats\",\r\n            \"se" +
            "asons\": \"1\",\r\n            \"episodes\": \"7\",\r\n            \"followers\": \"6\"\r\n      " +
            "  },\r\n        {\r\n            \"id\": \"5394\",\r\n            \"thetvdb_id\": \"80200\",\r\n" +
            "            \"imdb_id\": \"\",\r\n            \"title\": \"8th and Ocean\",\r\n            \"" +
            "seasons\": \"1\",\r\n            \"episodes\": \"10\",\r\n            \"followers\": \"1\"\r\n   " +
            "     },\r\n        {\r\n            \"id\": \"3314\",\r\n            \"thetvdb_id\": \"131541" +
            "\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"9 End 2 Outs \",\r\n         " +
            "   \"seasons\": \"1\",\r\n            \"episodes\": \"16\",\r\n            \"followers\": \"17\"" +
            "\r\n        },\r\n        {\r\n            \"id\": \"9726\",\r\n            \"thetvdb_id\": \"2" +
            "79194\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"90 Minutes Enqu\\u00ea" +
            "tes\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"1\",\r\n            \"f" +
            "ollowers\": \"1\"\r\n        },\r\n        {\r\n            \"id\": \"503\",\r\n            \"th" +
            "etvdb_id\": \"82716\",\r\n            \"imdb_id\": \"tt1225901\",\r\n            \"title\": \"" +
            "90210\",\r\n            \"seasons\": \"5\",\r\n            \"episodes\": \"114\",\r\n          " +
            "  \"followers\": \"26487\"\r\n        },\r\n        {\r\n            \"id\": \"10346\",\r\n     " +
            "       \"thetvdb_id\": \"262366\",\r\n            \"imdb_id\": \"\",\r\n            \"title\":" +
            " \"999: What\'s Your Emergency?\",\r\n            \"seasons\": \"2\",\r\n            \"episo" +
            "des\": \"16\",\r\n            \"followers\": \"0\"\r\n        },\r\n        {\r\n            \"i" +
            "d\": \"8953\",\r\n            \"thetvdb_id\": \"270982\",\r\n            \"imdb_id\": \"\",\r\n  " +
            "          \"title\": \"=3\",\r\n            \"seasons\": \"5\",\r\n            \"episodes\": \"" +
            "435\",\r\n            \"followers\": \"11\"\r\n        },\r\n        {\r\n            \"id\": \"" +
            "8064\",\r\n            \"thetvdb_id\": \"274099\",\r\n            \"imdb_id\": \"tt3279494\"," +
            "\r\n            \"title\": \"@midnight\",\r\n            \"seasons\": \"3\",\r\n            \"e" +
            "pisodes\": \"219\",\r\n            \"followers\": \"15\"\r\n        },\r\n        {\r\n        " +
            "    \"id\": \"2528\",\r\n            \"thetvdb_id\": \"79958\",\r\n            \"imdb_id\": \"\"" +
            ",\r\n            \"title\": \"A 4x4 Is Born\",\r\n            \"seasons\": \"1\",\r\n         " +
            "   \"episodes\": \"15\",\r\n            \"followers\": \"4\"\r\n        },\r\n        {\r\n     " +
            "       \"id\": \"2716\",\r\n            \"thetvdb_id\": \"150601\",\r\n            \"imdb_id\"" +
            ": \"tt1625107\",\r\n            \"title\": \"A Band for Britain\",\r\n            \"seasons" +
            "\": \"1\",\r\n            \"episodes\": \"3\",\r\n            \"followers\": \"1\"\r\n        },\r" +
            "\n        {\r\n            \"id\": \"2641\",\r\n            \"thetvdb_id\": \"78806\",\r\n     " +
            "       \"imdb_id\": \"tt0457224\",\r\n            \"title\": \"A Bear\'s Tail\",\r\n         " +
            "   \"seasons\": \"1\",\r\n            \"episodes\": \"6\",\r\n            \"followers\": \"0\"\r\n" +
            "        },\r\n        {\r\n            \"id\": \"2585\",\r\n            \"thetvdb_id\": \"109" +
            "111\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"A Bear\'s Tale\",\r\n      " +
            "      \"seasons\": \"1\",\r\n            \"episodes\": \"6\",\r\n            \"followers\": \"0" +
            "\"\r\n        },\r\n        {\r\n            \"id\": \"6634\",\r\n            \"thetvdb_id\": \"" +
            "266446\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"A Beautiful Affair\"," +
            "\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"5\",\r\n            \"follow" +
            "ers\": \"0\"\r\n        },\r\n        {\r\n            \"id\": \"6633\",\r\n            \"thetvd" +
            "b_id\": \"79957\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"A Bike Is Bor" +
            "n\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"15\",\r\n            \"fo" +
            "llowers\": \"0\"\r\n        },\r\n        {\r\n            \"id\": \"2864\",\r\n            \"th" +
            "etvdb_id\": \"92001\",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"A Biograp" +
            "hy of America\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"26\",\r\n   " +
            "         \"followers\": \"1\"\r\n        },\r\n        {\r\n            \"id\": \"594\",\r\n    " +
            "        \"thetvdb_id\": \"71040\",\r\n            \"imdb_id\": \"tt0101049\",\r\n           " +
            " \"title\": \"A Bit of Fry and Laurie\",\r\n            \"seasons\": \"4\",\r\n            \"" +
            "episodes\": \"25\",\r\n            \"followers\": \"131\"\r\n        },\r\n        {\r\n       " +
            "     \"id\": \"6592\",\r\n            \"thetvdb_id\": \"107451\",\r\n            \"imdb_id\": " +
            "null,\r\n            \"title\": \"A Bride For A Ride\",\r\n            \"seasons\": \"1\",\r\n" +
            "            \"episodes\": \"21\",\r\n            \"followers\": \"0\"\r\n        },\r\n       " +
            " {\r\n            \"id\": \"3241\",\r\n            \"thetvdb_id\": \"248012\",\r\n            " +
            "\"imdb_id\": \"tt1908018\",\r\n            \"title\": \"A Bridge to the Starry Skies\",\r\n " +
            "           \"seasons\": \"1\",\r\n            \"episodes\": \"12\",\r\n            \"follower" +
            "s\": \"15\"\r\n        },\r\n        {\r\n            \"id\": \"7904\",\r\n            \"thetvdb" +
            "_id\": \"82446\",\r\n            \"imdb_id\": \"tt1100910\",\r\n            \"title\": \"A Buc" +
            "ket O\' French and Saunders\",\r\n            \"seasons\": \"1\",\r\n            \"episodes" +
            "\": \"6\",\r\n            \"followers\": \"2\"\r\n        },\r\n        {\r\n            \"id\": " +
            "\"9142\",\r\n            \"thetvdb_id\": \"283082\",\r\n            \"imdb_id\": \"\",\r\n      " +
            "      \"title\": \"A Cabbie Abroad\",\r\n            \"seasons\": \"1\",\r\n            \"epi" +
            "sodes\": \"3\",\r\n            \"followers\": \"1\"\r\n        },\r\n        {\r\n            \"" +
            "id\": \"6611\",\r\n            \"thetvdb_id\": \"79953\",\r\n            \"imdb_id\": \"\",\r\n  " +
            "          \"title\": \"A Car Is Born\",\r\n            \"seasons\": \"1\",\r\n            \"e" +
            "pisodes\": \"15\",\r\n            \"followers\": \"0\"\r\n        },\r\n        {\r\n          " +
            "  \"id\": \"2775\",\r\n            \"thetvdb_id\": \"79954\",\r\n            \"imdb_id\": \"\",\r" +
            "\n            \"title\": \"A Car Is Reborn\",\r\n            \"seasons\": \"1\",\r\n         " +
            "   \"episodes\": \"15\",\r\n            \"followers\": \"2\"\r\n        },\r\n        {\r\n     " +
            "       \"id\": \"2795\",\r\n            \"thetvdb_id\": \"101321\",\r\n            \"imdb_id\"" +
            ": \"tt0348904\",\r\n            \"title\": \"A Casa das Sete Mulheres\",\r\n            \"s" +
            "easons\": \"1\",\r\n            \"episodes\": \"52\",\r\n            \"followers\": \"4\"\r\n    " +
            "    },\r\n        {\r\n            \"id\": \"2825\",\r\n            \"thetvdb_id\": \"173031\"" +
            ",\r\n            \"imdb_id\": \"\",\r\n            \"title\": \"A Century of Fatherhood\",\r\n" +
            "            \"seasons\": \"1\",\r\n            \"episodes\": \"3\",\r\n            \"follower" +
            "s\": \"0\"\r\n        },\r\n        {\r\n            \"id\": \"6648\",\r\n            \"thetvdb_" +
            "id\": \"261688\",\r\n            \"imdb_id\": \"tt0466438\",\r\n            \"title\": \"A Cen" +
            "tury of Flight\",\r\n            \"seasons\": \"1\",\r\n            \"episodes\": \"3\",\r\n   " +
            "         \"followers\": \"0\"\r\n        },\r\n       ")]
        public string SeriesList {
            get {
                return ((string)(this["SeriesList"]));
            }
        }
    }
}
